version: '3'
services:

  database:
    image: postgres:16.3
    env_file: 
      - .env
    # only for debug
    #ports:
    #  - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./movies_database_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always

  backend:
    build: src
    ports:
      - "80:80"
    env_file: 
      - .env
    depends_on:
      - database
    restart: always

  redis:
    image: redis:7.4.0
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    # only for debug
    # ports:
    #  - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

  postgres_to_es:
    build: postgres_to_es
    env_file: 
      - .env
    depends_on:
      - database
      - elasticsearch
    volumes:
      - ./state.json:/app/state.json
      - ./logs:/app/logs
    restart: always

volumes:
  esdata:
    driver: local