"""Initial migration for NotificationModel

Revision ID: 5bbbd2430300
Revises: 
Create Date: 2024-11-09 16:07:25.035061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbbd2430300'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_notification_send', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
