logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  scan_frequency: 10s
  paths:
    - /var/log/nginx/*
  tags: ["nginx"]
  fields:
    service: "nginx"
    environment: "production"
  json:
    keys_under_root: true
    add_error_key: true
    message_key: "log"
    ignore_missing: true

  processors:
    - decode_json_fields:
        fields: ["message"]
        process_array: false
        max_depth: 2
        target: ""
        overwrite_keys: true
        add_error_key: false

output.logstash:
  enabled: true
  hosts: ["logstash:5045"] 